### PR TITLE
Ping

### PR DESCRIPTION
**Pull request by ptzianos**
A plugin for getting stats on droprate and average roundtrip time when pinging an address

### CODE REVIEW

**Comment by ymettier** [comment]
Hello,

Some comments on this PR that will probably be merged first.
First comment : nice plugin, good job !

# config/default.json #

Always think that some users may overwrite or append some servers in `config/local.json`.
I have noticed that lists of configuration elements should not be coded as lists (with [] brackets) but as hashs.
In your example, if `default.json` contains `"hosts": ["www.bing.com"]` and some user writes a `local.json` containing `"hosts": ["www.google.com"]`, the result will be only "www.google.com".
If you are using a hash, elements of the hash from local.json will be added to the hash of `default.json`.

In other words, I suggest this kind of configuration (default.json) : 
```
"ping": {
	        "enable": 1,
// This is an example. If you want to change which url is pinged you can do so like shown below:
//There is no limit to how many addresses can be pinged. They have to be all in an array.
	        "hosts": {
                      "www.bing.com": 1
	        }
	    }
```

Then, if someone wants to add something, here is how it may look in local.json : 

```
"ping": {
	        "enable": 1,
	        "hosts": {
                      "www.google.com": 1
	        }
	    }
```
The result is to have both bing and google.

You noticed that I put a value `1`. My idea is to enable/disable that server. Keeping the default.json configuration file with bing enabled, if somewone writes this : 
```
"ping": {
	        "enable": 1,
	        "hosts": {
                      "www.google.com": 1
                      "www.bing.com": 0
	        }
	    }
```
The expected behaviour should be to enable google and disable bing, even if bing was enabled in default.json.

With lists, such behaviour is impossible.

You can read more about how it works here : https://github.com/lorenwest/node-config

# package.json #
Note for me : do not forget to include ping-output.

More general thoughs : 
* how can we do to package Collectm with a set of plugins and how to package additionnal plugins (including their dependancies) outside of Collectm for more modularity (and for those who want to package their plugins themselves) ?
* how can we do if 2 versions of a same npm module conflicts, one module version for one integrated plugin and one module version for an external plugin ?

Of course, this has not happened yet, is not a problem today, and will not prevent from merging this PR to master branch.

# src/collectm.nsi #

Please indent better line 151 (replace a tab with spaces ?) : 
```
SetOutPath $InstDir\node_modules\ping-output
```

# src/plugins/ping.js #

## hosts array ##
```
var hosts = [
    {
        host: "www.bing.com"
    }
];
```

This list should be empty.
You should check at start time if this list is empty or not. If yes, disable the plugin (and write in the log that it was disabled).
You can disable the plugin by returning a non-nul value in reloadConfig() method.

## Log as much as possible ##

Use logger.log('info', ...) to log what hosts are ping'ed. This may help people in production teams to understand why they do not have results for one server, one day.


Regards,
Yves

**Comment by ptzianos** [comment]
On 28-Apr-15 3:33 PM, ymettier wrote:
>
> Hello,
>
> Some comments on this PR that will probably be merged first.
> First comment : nice plugin, good job !
>
>
>   config/default.json
>
> Always think that some users may overwrite or append some servers in 
> |config/local.json|.
> I have noticed that lists of configuration elements should not be 
> coded as lists (with [] brackets) but as hashs.
> In your example, if |default.json| contains |"hosts": 
> ["www.bing.com"]| and some user writes a |local.json| containing 
> |"hosts": ["www.google.com"]|, the result will be only "www.google.com".
> If you are using a hash, elements of the hash from local.json will be 
> added to the hash of |default.json|.
>
> In other words, I suggest this kind of configuration (default.json) :
>
> |"ping": {
>              "enable": 1,
> // This is an example. If you want to change which url is pinged you can do so like shown below:
> //There is no limit to how many addresses can be pinged. They have to be all in an array.
>              "hosts": {
>                        "www.bing.com": 1
>              }
>          }
> |
>
> Then, if someone wants to add something, here is how it may look in 
> local.json :
>
> |"ping": {
>              "enable": 1,
>              "hosts": {
>                        "www.google.com": 1
>              }
>          }
> |
>
> The result is to have both bing and google.
>
> You noticed that I put a value |1|. My idea is to enable/disable that 
> server. Keeping the default.json configuration file with bing enabled, 
> if somewone writes this :
>
> |"ping": {
>              "enable": 1,
>              "hosts": {
>                        "www.google.com": 1
>                        "www.bing.com": 0
>              }
>          }
> |
>
> The expected behaviour should be to enable google and disable bing, 
> even if bing was enabled in default.json.
>
> With lists, such behaviour is impossible.
>
> You can read more about how it works here : 
> https://github.com/lorenwest/node-config
>
>
>   package.json
>
> Note for me : do not forget to include ping-output.
>
> More general thoughs :
>
>   * how can we do to package Collectm with a set of plugins and how to
>     package additionnal plugins (including their dependancies) outside
>     of Collectm for more modularity (and for those who want to package
>     their plugins themselves) ?
>   * how can we do if 2 versions of a same npm module conflicts, one
>     module version for one integrated plugin and one module version
>     for an external plugin ?
>
> Of course, this has not happened yet, is not a problem today, and will 
> not prevent from merging this PR to master branch.
>
>
>   src/collectm.nsi
>
> Please indent better line 151 (replace a tab with spaces ?) :
>
> |SetOutPath $InstDir\node_modules\ping-output
> |
>
>
>   src/plugins/ping.js
>
>
>     hosts array
>
> |var hosts = [
>      {
>          host: "www.bing.com"
>      }
> ];
> |
>
> This list should be empty.
> You should check at start time if this list is empty or not. If yes, 
> disable the plugin (and write in the log that it was disabled).
> You can disable the plugin by returning a non-nul value in 
> reloadConfig() method.
>
>
>     Log as much as possible
>
> Use logger.log('info', ...) to log what hosts are ping'ed. This may 
> help people in production teams to understand why they do not have 
> results for one server, one day.
>
> Regards,
> Yves
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/perfwatcher/collectm/pull/11#issuecomment-97046837>.
>
Ok, thanks for the reply. Starting to work on all your recommendations 
on ping and disk plugins.

Cheers,
Pavlos

**Comment by ymettier** [comment]
Merged into "modularization" branch. Will be merged in master later. See PR #13 for more information.

Thanks for your patch.

Regards,
Yves

**Comment by ymettier** [comment]
Sorry... I removed this plugin from the 1.6.0rc2 pre-release.
Here are the reasons :
* I need to do more tests and release 1.6.0 soon. And the Ping plugin makes problems for me. See below
* stddev : I fixed a bug, but are there any others ?
* ping.exe gives us some results we do not trust. We need to investigate more.
* the ping plugin does not take care of the Collectd interval. It pings and pings and pings and never stop. I'm not convinced that launching `runPings()` at `ping:exit_code` is not the best way to do it. Using setInterval may be better but you have to ensure that you don't run too many pings inside one Collectd interval (which may be 60s or used-defined to something that can even be 1 second !).
* Configuration of the plugin should not be in the `.monitor` method.


I keep this PR closed.
If you want to improve the plugin, please start a new PR from branch ping_plugin that I isolated to make the work easier for everybody.

Regards,
Yves

**Pull request closed without merging**
