### PR TITLE
Modularization

### PR DESCRIPTION
**Pull request by ptzianos**
This change in the collectdCompat plugin allows the user to select which of the metrics of plugin will be enabled. It was needed initially to make sure that the new load and disk plugins will not have any conflict with the existing functionality but it might come handy for other users in the future.

### CODE REVIEW

**Comment by ymettier** [comment]
Hello,

I do not like this patch.
I do not like collectdCompat plugin (but it was a great start for Collectm)
I like your plugins Load and Disk.

I'd prefer that you remove completely Load and Disk from collectdCompat.
And when the other plugins are also coded outside of collectdCompat, get rid of collectdCompat.

If you want to code the other plugins that are currently in collectdCompat, please do it.
Otherwise, we will keep them in collectdCompat until someone does it.

Could you provide another PR for collectdCompat with Disk and Load removed ?

The general idea is to avoid duplicate code.

Does that make sense ?

Regards,
Yves

**Comment by ptzianos** [comment]
On 28-Apr-15 3:44 PM, ymettier wrote:
>
> Hello,
>
> I do not like this patch.
> I do not like collectdCompat plugin (but it was a great start for 
> Collectm)
> I like your plugins Load and Disk.
>
> I'd prefer that you remove completely Load and Disk from collectdCompat.
> And when the other plugins are also coded outside of collectdCompat, 
> get rid of collectdCompat.
>
> If you want to code the other plugins that are currently in 
> collectdCompat, please do it.
> Otherwise, we will keep them in collectdCompat until someone does it.
>
> Could you provide another PR for collectdCompat with Disk and Load 
> removed ?
>
> The general idea is to avoid duplicate code.
>
> Does that make sense ?
>
> Regards,
> Yves
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/perfwatcher/collectm/pull/13#issuecomment-97048862>.
>
Yeah sure. I did this patch trying to make the least amount of changes 
to your code as possible and avoid conflicts. But i have no problem 
removing load and disks from collectdCompat. Do you want me to leave the 
changes that allow for choosing which metrics of collectdCompat will be 
active or do you want me to remove those lines too?

Cheers,
Pavlos

**Comment by ymettier** [comment]
I added the tag "wontfix" but I'm not sure that's the correct tag.

> Do you want me to leave the
> changes that allow for choosing which metrics of collectdCompat will be
> active or do you want me to remove those lines too?

The main idea is : no duplicate.
The other idea is : make collectdCompat plugin obsolete by creating dedicated plugins.

I think the best solution is to have as less configuration as possible on collectdCompat plugin in order to make it obsolete as soon as possible without migration work. So yes, please remove any configuration parameter you may have added to collectdCompat plugin.

Regards,
Yves

**Comment by ptzianos** [comment]
On 06/05/2015 06:28 μμ, ymettier wrote:
>
> I added the tag "wontfix" but I'm not sure that's the correct tag.
>
>     Do you want me to leave the
>     changes that allow for choosing which metrics of collectdCompat
>     will be
>     active or do you want me to remove those lines too?
>
> The main idea is : no duplicate.
> The other idea is : make collectdCompat plugin obsolete by creating 
> dedicated plugins.
>
> I think the best solution is to have as less configuration as possible 
> on collectdCompat plugin in order to make it obsolete as soon as 
> possible without migration work. So yes, please remove any 
> configuration parameter you may have added to collectdCompat plugin.
>
> Regards,
> Yves
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/perfwatcher/collectm/pull/13#issuecomment-99514183>.
>
If you could leave the code that allows the user to choose which 
collectdCompat metrics are being used that we be perfect. We are already 
having people interested in the platform now that it supports Windows 
integration so soon we will have some real world requirements about what 
they need and we will revisit the project to add more plugins. But that 
will happen in a couple of months. And I just realized I haven't removed 
the launch_collector_load function and I just removed the call to the 
function. Sorry :).

Cheers,
Pavlos.

**Comment by ymettier** [comment]
Hello,

I created a new branch named modularization.
Here are the first lines of new ChangeLog : 
```
- PR #10 : added Load plugin (Thanks to Paul Tzianos)
- PR #11 : added Ping plugin (Thanks to Paul Tzianos)
- PR #12 : added Disk plugin (Thanks to Paul Tzianos)
- PR #15 : added Df plugin (Thanks to Paul Tzianos)
- PR #13 (1) : removed duplicate modules from collectdCompat plugin (Thanks to Paul Tzianos)
- PR #13 (2) : some modules of CollectdCompat plugin are now optional (Thanks to Paul Tzianos)
```

I will now close PR #10, PR #11, PR #12 and PR #15.
I keep this PR open until I merge the "modularization" branch into master.

Notes about the merge :
* I kept your code in collectdCompat as you requested.
* You should run `grunt test` in order to test the syntax (thanks to jshint) before sending any PR
* jshint noticed 2 syntax errors (missing semicolon at the end of lines)
* jshint complains about double quotes. You should use single quotes instead.
* jshint complains about some vars['xyz'] that should be better written vars.xyz
* jshint complains about some `== 0` or `== true` comparizons that should better be written as `=== 0` or `=== true`.

I fixed all those jshint complains.

I also included ping-output npm module into Collectm.

Because the merging of all your PR confliced on default.json configuration file, I'd prefer that we now work on the modularization branch in order to fix what is not working yet (load : see below). That's why I close the other PR.

Last problem : load plugin crashed as soon as I started Collectm. More info about that will follow.

Regards,
Yves

**Comment by ymettier** [comment]
Hello again,

It seems that Collectm (branch modularization) works well with load disabled.

When load is enabled, I have a crash : 
```
2015-05-07T10:02:13.951Z - error: uncaughtException: Cannot read property 'push' of undefined 
{ date: 'Thu May 07 2015 12:02:13 GMT+0200 (Romance Daylight Time)',
  process: 
   { pid: 9828,
     uid: null,
     gid: null,
     cwd: 'C:\\Program Files\\CollectM\\bin',
     execPath: 'C:\\Program Files\\CollectM\\bin\\node.exe',
     version: 'v0.12.0',
     argv: 
      [ 'C:\\Program Files\\CollectM\\bin\\node.exe',
        'C:\\Program Files\\CollectM\\lib\\collectm.js' ],
     memoryUsage: { rss: 35254272, heapTotal: 30566144, heapUsed: 11902224 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 158377.3316014 },
  trace: 
   [ { column: 71,
       file: 'Files\\CollectM\\plugins\\load.js',
       function: 'Object.cb (C:\\Program',
       line: 103,
       method: 'cb (C:\\Program',
       native: false },
     { column: 11,
       file: 'Files\\CollectM\\node_modules\\perfmon\\perfmon.js',
       function: 'PerfmonStream.<anonymous> (C:\\Program',
       line: 133,
       method: '<anonymous> (C:\\Program',
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'PerfmonStream.emit',
       line: 107,
       method: 'emit',
       native: false },
     { column: 8,
       file: 'Files\\CollectM\\node_modules\\perfmon\\lib\\PerfmonStream.js',
       function: 'PerfmonStream.write (C:\\Program',
       line: 66,
       method: 'write (C:\\Program',
       native: false },
     { column: 8,
       file: 'Files\\CollectM\\node_modules\\perfmon\\lib\\PerfmonStream.js',
       function: 'TypePerf.<anonymous> (C:\\Program',
       line: 20,
       method: '<anonymous> (C:\\Program',
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'TypePerf.emit',
       line: 129,
       method: 'emit',
       native: false },
     { column: 8,
       file: 'Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js',
       function: 'update (C:\\Program',
       line: 209,
       method: null,
       native: false },
     { column: 11,
       file: 'Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js',
       function: 'C:\\Program',
       line: 220,
       method: null,
       native: false },
     { column: null,
       file: null,
       function: 'Array.some',
       line: null,
       method: 'some',
       native: true },
     { column: 9,
       file: 'Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js',
       function: 'Socket.<anonymous> (C:\\Program',
       line: 218,
       method: '<anonymous> (C:\\Program',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'push\' of undefined',
     '    at Object.cb (C:\\Program Files\\CollectM\\plugins\\load.js:103:71)',
     '    at PerfmonStream.<anonymous> (C:\\Program Files\\CollectM\\node_modules\\perfmon\\perfmon.js:133:11)',
     '    at PerfmonStream.emit (events.js:107:17)',
     '    at PerfmonStream.write (C:\\Program Files\\CollectM\\node_modules\\perfmon\\lib\\PerfmonStream.js:66:8)',
     '    at TypePerf.<anonymous> (C:\\Program Files\\CollectM\\node_modules\\perfmon\\lib\\PerfmonStream.js:20:8)',
     '    at TypePerf.emit (events.js:129:20)',
     '    at update (C:\\Program Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js:209:8)',
     '    at C:\\Program Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js:220:11',
     '    at Array.some (native)',
     '    at Socket.<anonymous> (C:\\Program Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js:218:9)' ] }
```

I hope that I have not introduced that bug while merging...

Do you have an idea ?

Regards,
Yves

**Comment by ptzianos** [comment]
On 07/05/15 13:04, ymettier wrote:
>
> Hello again,
>
> It seems that Collectm (branch modularization) works well with load 
> disabled.
>
> When load is enabled, I have a crash :
>
> |2015-05-07T10:02:13.951Z - error: uncaughtException: Cannot read property 'push' of undefined
> { date: 'Thu May 07 2015 12:02:13 GMT+0200 (Romance Daylight Time)',
>    process:
>     { pid: 9828,
>       uid: null,
>       gid: null,
>       cwd: 'C:\\Program Files\\CollectM\\bin',
>       execPath: 'C:\\Program Files\\CollectM\\bin\\node.exe',
>       version: 'v0.12.0',
>       argv:
>        [ 'C:\\Program Files\\CollectM\\bin\\node.exe',
>          'C:\\Program Files\\CollectM\\lib\\collectm.js' ],
>       memoryUsage: { rss: 35254272, heapTotal: 30566144, heapUsed: 11902224 } },
>    os: { loadavg: [ 0, 0, 0 ], uptime: 158377.3316014 },
>    trace:
>     [ { column: 71,
>         file: 'Files\\CollectM\\plugins\\load.js',
>         function: 'Object.cb (C:\\Program',
>         line: 103,
>         method: 'cb (C:\\Program',
>         native: false },
>       { column: 11,
>         file: 'Files\\CollectM\\node_modules\\perfmon\\perfmon.js',
>         function: 'PerfmonStream.<anonymous> (C:\\Program',
>         line: 133,
>         method: '<anonymous> (C:\\Program',
>         native: false },
>       { column: 17,
>         file: 'events.js',
>         function: 'PerfmonStream.emit',
>         line: 107,
>         method: 'emit',
>         native: false },
>       { column: 8,
>         file: 'Files\\CollectM\\node_modules\\perfmon\\lib\\PerfmonStream.js',
>         function: 'PerfmonStream.write (C:\\Program',
>         line: 66,
>         method: 'write (C:\\Program',
>         native: false },
>       { column: 8,
>         file: 'Files\\CollectM\\node_modules\\perfmon\\lib\\PerfmonStream.js',
>         function: 'TypePerf.<anonymous> (C:\\Program',
>         line: 20,
>         method: '<anonymous> (C:\\Program',
>         native: false },
>       { column: 20,
>         file: 'events.js',
>         function: 'TypePerf.emit',
>         line: 129,
>         method: 'emit',
>         native: false },
>       { column: 8,
>         file: 'Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js',
>         function: 'update (C:\\Program',
>         line: 209,
>         method: null,
>         native: false },
>       { column: 11,
>         file: 'Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js',
>         function: 'C:\\Program',
>         line: 220,
>         method: null,
>         native: false },
>       { column: null,
>         file: null,
>         function: 'Array.some',
>         line: null,
>         method: 'some',
>         native: true },
>       { column: 9,
>         file: 'Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js',
>         function: 'Socket.<anonymous> (C:\\Program',
>         line: 218,
>         method: '<anonymous> (C:\\Program',
>         native: false } ],
>    stack:
>     [ 'TypeError: Cannot read property \'push\' of undefined',
>       '    at Object.cb (C:\\Program Files\\CollectM\\plugins\\load.js:103:71)',
>       '    at PerfmonStream.<anonymous> (C:\\Program Files\\CollectM\\node_modules\\perfmon\\perfmon.js:133:11)',
>       '    at PerfmonStream.emit (events.js:107:17)',
>       '    at PerfmonStream.write (C:\\Program Files\\CollectM\\node_modules\\perfmon\\lib\\PerfmonStream.js:66:8)',
>       '    at TypePerf.<anonymous> (C:\\Program Files\\CollectM\\node_modules\\perfmon\\lib\\PerfmonStream.js:20:8)',
>       '    at TypePerf.emit (events.js:129:20)',
>       '    at update (C:\\Program Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js:209:8)',
>       '    at C:\\Program Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js:220:11',
>       '    at Array.some (native)',
>       '    at Socket.<anonymous> (C:\\Program Files\\CollectM\\node_modules\\perfmon\\lib\\TypePerf.js:218:9)' ] }
> |
>
> I hope that I have not introduced that bug while merging...
>
> Do you have an idea ?
>
> Regards,
> Yves
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/perfwatcher/collectm/pull/13#issuecomment-99802046>.
>
Ok, no worries I'll have a look at it in a couple of hours. I'm sure 
it's something small and I'll do a new pull request with the fix.

Cheers,
Pavlos.

**Pull request closed without merging**
